steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t europe-southwest1-docker.pkg.dev/store-microservices-428520/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'europe-southwest1-docker.pkg.dev/store-microservices-428520/image-registry/orders-ms',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/916489976505/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'